version: '1.0'

networks:
  my-network: 
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.56.0/24
services:
  python:
    build : .
    # image: tensorflow/tensorflow:latest
    container_name: tensorflow
    # environment:
    #   POSTGRES_USER: web
    #   POSTGRES_PASSWORD: postgres_pw
    #   POSTGRES_DB: exam
    volumes:
      #- /Users/work6189/Documents/project/db/postgres_data:/var/lib/postgresql/data
      - ./:/app/
    ports:
      - "8888:8888"
    command: ""
    networks:
      my-network:
        ipv4_address: 192.168.56.11

